#!/bin/bash

for dir in stemcells/*; do
  echo ${dir}:
  ls -la ${dir}
  stemcell=$(echo ${dir} | sed 's|stemcells/||')
  version=$(cat ${dir}/version)
  target_md5=$(curl https://bosh.io/api/v1/stemcells/${stemcell} | jq -r ". | map(select(.version == \"${version}\")) | .[] | .light // .regular | .md5")
  actual_md5=$(md5sum ${dir}/stemcell.tgz | cut -d " " -f1)

  if [[ "$actual_md5" != "${target_md5}" ]]; then
    echo "md5sum mismatch between what bosh.io says (${target_md5}), and what we calculated (${actual_md5}). Aborting."
    exit 1
  fi

  sha1=$(shasum -a 1 ${dir}/stemcell.tgz | cut -d " " -f1)

  mkdir -p ${REPO_ROOT}/www/${stemcell}
  echo ${sha1} > ${REPO_ROOT}/www/${stemcell}/${version}
done

# GIT!
if [[ -z $(git config --global user.email) ]]; then
  git config --global user.email "ci@starkandwayne.com"
fi
if [[ -z $(git config --global user.name) ]]; then
  git config --global user.name "CI Bot"
fi

pushd ${REPO_ROOT}
git merge --no-edit ${BRANCH}
git add www
git commit -m "Updating sha1s"
popd

cp -a ${REPO_ROOT} ${REPO_OUT}
