---
meta:
  cf:
    user: (( vault "secret/pipelines/stemcell-sha1s/cf:user" ))
    pass: (( vault "secret/pipelines/stemcell-sha1s/cf:password" ))
    org: (( vault "secret/pipelines/stemcell-sha1s/cf:org" ))
    space: (( vault "secret/pipelines/stemcell-sha1s/cf:space" ))
    app: (( vault "secret/pipelines/stemcell-sha1s/cf:app" ))

  github:
    private_key: (( vault "secret/pipelines/stemcell-sha1s/git:private" ))
